import * as React from 'react'
import { LayoutProps } from '../../models/common'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import TopBar from '../TopBar/topBar'

export function MainLayout({ children }: LayoutProps) {
  return (
    <div className="bg-white text-black">
      <Head>
        <title>Mandy || CV Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex flex-1 flex-col">
        <TopBar />
        {children}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
