import Head from 'next/head'
import Image from 'next/image'
import ExperienceDetail from '../components/Experience/experienceDetail'
import ProductDetailList from '../components/Product/productDetailList'
import Review from '../components/Review/review'
import RightProduct from '../components/RightProduct/rightProduct'
import TopBar from '../components/TopBar/topBar'
import SomeProject from '../components/TrustOnMe/someProject'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mandy || CV Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TopBar />
        <SomeProject />
        <ExperienceDetail />
        <ProductDetailList />
        <RightProduct />
        <Review />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// export async function getServerSideProps() {
//   return {
//     props: {},
//   }
// }
